language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn global add lerna
  - yarn global add codecov
  - lerna bootstrap

matrix:
  include:
    - name: Common Pipeline
      env: PACKAGE_LOCATION=packages/common PACKAGE_NAME=pascalcoin-sbx-common
    - name: Crypto Pipeline
      env: PACKAGE_LOCATION=packages/crypto PACKAGE_NAME=pascalcoin-sbx-crypto

script:
  - cd $PACKAGE_LOCATION
